=begin
#QueryBuilderApi

#Active Query Builder Web API lets create, analyze and modify SQL queries for different database servers using RESTful HTTP requests to a cloud-based service. It requires SQL execution context (information about database schema and used database server) to be stored under the registered account at https://webapi.activequerybuilder.com/.

OpenAPI spec version: 1.1.8
Contact: support@activedbsoft.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

# Common files
require 'webapi-active-query-builder/api_client'
require 'webapi-active-query-builder/api_error'
require 'webapi-active-query-builder/version'
require 'webapi-active-query-builder/configuration'

# Models
require 'webapi-active-query-builder/models/condition'
require 'webapi-active-query-builder/models/condition_group'
require 'webapi-active-query-builder/models/hidden_column'
require 'webapi-active-query-builder/models/pagination'
require 'webapi-active-query-builder/models/query_column'
require 'webapi-active-query-builder/models/sorting'
require 'webapi-active-query-builder/models/sql_query'
require 'webapi-active-query-builder/models/totals'
require 'webapi-active-query-builder/models/transform'
require 'webapi-active-query-builder/models/transform_result'

# APIs
require 'webapi-active-query-builder/api/active_query_builder_api'

module WebApiActivequerybuilder
  class << self
    # Customize default settings for the SDK using block.
    #   WebApiActivequerybuilder.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
